// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxZ5dsX1dPgkoiDzG3OPgUxA3nEsZAd28',
    appId: '1:1080969109122:web:6b439b400455b3394fde9b',
    messagingSenderId: '1080969109122',
    projectId: 'fir-crud-basics-72af0',
    authDomain: 'fir-crud-basics-72af0.firebaseapp.com',
    storageBucket: 'fir-crud-basics-72af0.firebasestorage.app',
    measurementId: 'G-LFM28DGE78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREhIs7NBOSj35LlNdEl48zz75Xnx4yY8',
    appId: '1:1080969109122:android:78404b8cf1cc7ac64fde9b',
    messagingSenderId: '1080969109122',
    projectId: 'fir-crud-basics-72af0',
    storageBucket: 'fir-crud-basics-72af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FU7S0Q5QnPZmR5B3VFbx3qvhJYCS4Ok',
    appId: '1:1080969109122:ios:10785eb45500659d4fde9b',
    messagingSenderId: '1080969109122',
    projectId: 'fir-crud-basics-72af0',
    storageBucket: 'fir-crud-basics-72af0.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FU7S0Q5QnPZmR5B3VFbx3qvhJYCS4Ok',
    appId: '1:1080969109122:ios:10785eb45500659d4fde9b',
    messagingSenderId: '1080969109122',
    projectId: 'fir-crud-basics-72af0',
    storageBucket: 'fir-crud-basics-72af0.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxZ5dsX1dPgkoiDzG3OPgUxA3nEsZAd28',
    appId: '1:1080969109122:web:87dd7b59296a3d0b4fde9b',
    messagingSenderId: '1080969109122',
    projectId: 'fir-crud-basics-72af0',
    authDomain: 'fir-crud-basics-72af0.firebaseapp.com',
    storageBucket: 'fir-crud-basics-72af0.firebasestorage.app',
    measurementId: 'G-3W1C91EEDP',
  );
}
