// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABjpRCMUpEdkhi3-42gWZUR-JGLp13TtE',
    appId: '1:452267324025:web:b0412b2c91c92de4d81aa8',
    messagingSenderId: '452267324025',
    projectId: 'trash-sorter-9c475',
    authDomain: 'trash-sorter-9c475.firebaseapp.com',
    storageBucket: 'trash-sorter-9c475.firebasestorage.app',
    measurementId: 'G-ZC9ZPZSGN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzZndWtWWyYEYuVBxhJAKLpsboSF4ED8',
    appId: '1:452267324025:android:38bfc211908a4b51d81aa8',
    messagingSenderId: '452267324025',
    projectId: 'trash-sorter-9c475',
    storageBucket: 'trash-sorter-9c475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBASFIeqwH7UmupaHWbHgIH_sVqcUaFBqM',
    appId: '1:452267324025:ios:e2b661cee4c0178cd81aa8',
    messagingSenderId: '452267324025',
    projectId: 'trash-sorter-9c475',
    storageBucket: 'trash-sorter-9c475.firebasestorage.app',
    iosBundleId: 'com.example.trashSorter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBASFIeqwH7UmupaHWbHgIH_sVqcUaFBqM',
    appId: '1:452267324025:ios:e2b661cee4c0178cd81aa8',
    messagingSenderId: '452267324025',
    projectId: 'trash-sorter-9c475',
    storageBucket: 'trash-sorter-9c475.firebasestorage.app',
    iosBundleId: 'com.example.trashSorter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABjpRCMUpEdkhi3-42gWZUR-JGLp13TtE',
    appId: '1:452267324025:web:428818abb1db927cd81aa8',
    messagingSenderId: '452267324025',
    projectId: 'trash-sorter-9c475',
    authDomain: 'trash-sorter-9c475.firebaseapp.com',
    storageBucket: 'trash-sorter-9c475.firebasestorage.app',
    measurementId: 'G-S688F43PQD',
  );
}
